url: https://demo.remark42.com # url to remark42 server, required
secret: secret-key # secret key, required

dev_passwd: dev-passwd # password for `dev` user, turning on dev mode with basic auth 
image_proxy: true # allow http>https image proxy, default false
port: 8080 # service port, default 8080
web_root: /srv/var/web 
read_only_age: 0

sites:
  - remark

storage:
  type: bolt
  bolt:
    location: /srv/var

admin:
  email: umputun@gmail.com
  ids:
    - github_1234567
    - github_0987654

auth:
  jwt_exp: 720h
  providers:
    - name: google
      cid: 1111111
      csec: 999999999
    - name: facebook
      cid: 11111111
      csec: 999999999
    - name: github
      cid: 11111111
      csec: 999999999

limits:
  max_body_size: 65000
  socket_timeout: 5m
  comment_size: 2000
  edit_duration: 5m

cache:
  type: mem
  items: 100
  value_max_size: 10000000
  cache_size: 5000000

backup:
  type: local
  local:
    location: /srv/var/backup
  max_files: 10
  duration: 24h
